# Generated by Django 5.2.4 on 2025-08-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile_pic',
            field=models.ImageField(upload_to='candidate/'),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
