# Generated by Django 5.2.4 on 2025-08-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_candidate_profile_pic_alter_usermaster_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='user_id',
            new_name='user',
        ),
    ]
