# Generated by Django 5.2.4 on 2025-08-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_user_id_candidate_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='user',
            new_name='user_id',
        ),
    ]
