# Generated by Django 5.2.4 on 2025-08-07 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_company_company_description_company_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_description',
            field=models.TextField(default='No description provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
