# Generated by Django 5.2.4 on 2025-08-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_applyjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='status',
            field=models.CharField(choices=[('Viewed', 'Viewed'), ('In Process', 'In Process'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Viewed', max_length=20),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='resume',
            field=models.FileField(upload_to='resume/'),
        ),
    ]
